### ISSUE TITLE
handle leading zero PSID's

### ISSUE THREAD

**Issue by ergz** [thesadie/sdwisard#11]
Assume user will enter a 7 digit psid and want to retrieve 7 digit psid's

Update the following:
* get_data needs to be updated so that when user supplies 7 digit psid it gets converted to the appropriate integer one that can be looked up on S3
* all of the metadata functions that handle PSID's need to return the PSID as a 7 digit when it is only 6.

Maybe instead of all this we can update the data on so that 7 digit psid's can be looked up.

**Comment by richpauloo** [comment]
I've given this some thought, and I think although it will work, I'd prefer to just update files in the S3 bucket and the package objects such that PSID is always a character of length 7, with left-padded zeros. 

Let's proceed with function development assuming the S3 bucket is fixed and that the package objects have been updated. I'll submit a PR to merge a new branch with the updated package objects to v0.1.
