### ISSUE TITLE
NA values in data objects

### ISSUE THREAD

**Issue by thesadie** [thesadie/sdwisard#7]
In the `water_systems` table there are NA values for `county` or `water_system_name`

In `psid_analyte` table there are NA values for `storet` and `analyte`

In `analytes` table there is one record with an NA `analyte`

Should we filter out these records from the data objects?

**Comment by richpauloo** [comment]
I need to think about this more in the morning and run some sanity checks. 

I think it should be okay, and recall seeing that these NA values impact << 1% of water systems.

**Comment by thesadie** [comment]
The NA values make returns from get water system ugly and less useful. I'm filtering them out inside the function.

**Comment by richpauloo** [comment]
I agree. By "I think it should be okay" I meant that it should be okay to filter them out in the objects because they only impact a small fraction of systems and analytes. I'll make a new branch and PR.
