### ISSUE TITLE
remove data.table dependency

### ISSUE THREAD

**Issue by thesadie** [thesadie/sdwisard#8]
The only function is [`data.table::fread`](https://github.com/Rdatatable/data.table/blob/4d849e03c3c0331a37ead3d9884406bf3715e716/R/fread.R)
looking at the source code, nothing too special going on. might be worth handling the download using base r to remove the dependency

```
# download temp file - download.file
# unzip file - gzfile
# read csv - read.csv
# return data frame
```

**Comment by thesadie** [comment]
If we do decide to remove dependency, do the package data objects need to be converted from data table data frames to plain data frames?

**Comment by richpauloo** [comment]
The package objects are all zipped up CSV files, so there's no need to convert underlying data structures (i.e., it's not .rds under the hood). We also don't need to unzip, as `read.csv()` does that on the fly.

The case for `fread()` v base R comes down to speed. I did some speed tests and `fread()` is about 3-4 times as fast on average compared to base R. I like the idea of being totally free of dependencies, but the data.table package is also very stable and I doubt fread will change much in the future. Are there other reasons to go base R?

```r
library(microbenchmark)
library(tidyverse)

# "big"   file, 1.1MB bytes 
big_file   <- "https://sdwis.s3.us-west-1.amazonaws.com/410002.csv.gz"

# "small" file, 11 KB
small_file <- "https://sdwis.s3.us-west-1.amazonaws.com/103041.csv.gz"

use_base_r <- function(file) {
  temp <- tempfile()
  download.file(file, temp)
  dat <- read.csv(temp)
  unlink(temp)
  return(dat)
}

use_fread <- function(file) {
  dat <- data.table::fread(file)
  return(dat)
}

mbm_small <- microbenchmark(
  use_base_r(small_file),
  use_fread(small_file),
  times = 10
)
autoplot(mbm_small)

mbm_big  <- microbenchmark(
  use_base_r(big_file),
  use_fread(big_file),
  times = 10
)
autoplot(mbm_big)
```

![small_mbm](https://user-images.githubusercontent.com/10336683/90843930-92827e80-e317-11ea-8b5c-af60a3b7bf68.png)

![big_mbm](https://user-images.githubusercontent.com/10336683/90843933-96ae9c00-e317-11ea-80b8-86086a9f29b8.png)


We may decide that these speed gains are minimal enough to go full base R. As shown above, for small files, the difference is almost imperceptible. But for larger files, it's the difference between a 1 sec or 3 sec function. I was curious, so I tried the biggest file we have (around 4-5 MB). It's about 15 sec v 5 sec on my machine, and fread has a nice progress bar when reading the file in. Not the end of the world to use read.csv though.

Here's the biggest file if you want to see for yourself:


```r
max_file <- "https://sdwis.s3.us-west-1.amazonaws.com/1910039.csv.gz"
use_base_r(max_file)
use_fread(max_file)
```

**Comment by thesadie** [comment]
Do we want to configure install to auto-install dependency?
